### ISSUE TITLE
Software Serial

### ISSUE THREAD

**Issue by chinzw** [RollingGecko/VescUartControl#5]
It seems that using SoftwareSerial to communicate with the VESC doesn't work. It would be great to get this working so that we can use the HardwareSerial for usb while connected to the VESC.

**Comment by RollingGecko** [comment]
Why don't I get an email about my issus. Sorry that I missed that. :(
You can get SoftwareSerial maybe to work if you slow down the baud rate on the VESC site rapidly. you can try it and give us a feedback about your success.

Regards

Andy
